Workspace: "工作空间"

Member: "成员"

MemberGroup: "成员组"

Alert Policy: "告警策略"

Bind Index: "绑定索引"

Black List: "黑名单"

Dashboard: "仪表盘"

Explorer: "查看器"

Intelligen Inspection: "智能巡检"

Monitor: "监控器"

Mute: "静默规则"

Note: "笔记"

Notification: "通知对象"

Pipeline: "文本处理"

SAML Configuration: "SAML配置"

SAML Mapping: "SAML映射"

Service Catalog: "服务清单"

Synthetic Custom Node: "拨测自建节点"

Workspace -> MemberGroup: "1 to N"
Workspace -> Member: "1 to N"
MemberGroup -> Member: "1 to N"
Workspace -> Alert Policy: "1 to N"
Alert Policy -> Member: "1 to N"
Alert Policy -> MemberGroup: "1 to N"
Alert Policy -> Notification: "1 to N"
Workspace -> Bind Index: "1 to N"
Workspace -> Black List: "1 to N"
Workspace -> Dashboard: "1 to N"
Workspace -> Explorer: "1 to N"
Workspace -> Intelligen Inspection: "1 to N"
Intelligen Inspection -> Alert Policy: "1 to N"
Workspace -> Monitor: "1 to N"
Monitor -> Dashboard: "1 to 1" 
Workspace -> Mute: "1 to N"
Workspace -> Note: "1 to N"
Workspace -> Notification: "1 to N"
Workspace -> Pipeline: "1 to N"
Workspace -> SAML Configuration: "1 to N"
Workspace -> SAML Mapping: "1 to N"
Workspace -> Service Catalog: "1 to N"
Workspace -> Synthetic Custom Node: "1 to N"