direction: right

RMS -> Protobuf: gen
RMS.style.3d: true

Developer -> RMS: write
Developer -> Protobuf: write

Protobuf -> Buf Generator -> Typescript

Protobuf.style.multiple: true

Developer.shape: circle
